spring:
  datasource:
    url: jdbc:mysql://localhost/desarrollo?serverTimezone=America/Lima&useSSL=false
    username: root
    password: burnout
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    time-zone: America/Lima
    locale: es_PE
logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080
